# Generated by Django 5.0.6 on 2025-10-13 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_appym_aptcr_apven_alter_bankdetails_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cif',
        ),
    ]
