# Generated by Django 5.0.6 on 2025-10-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_users_cif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='bicCode',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bankdetails',
            name='sort_code',
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='bank_code',
            field=models.CharField(default=1430, max_length=255, verbose_name='Bank Code'),
            preserve_default=False,
        ),
    ]
