# Generated by Django 5.0.6 on 2025-10-15 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='webapp.projects'),
        ),
        migrations.AddField(
            model_name='processeddeposits',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='processed_deposits', to='webapp.projects'),
        ),
    ]
