# Generated by Django 5.0.6 on 2025-10-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_bankdetails_project_processeddeposits_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddeposits',
            name='batch_identifier',
            field=models.CharField(default='5674883', max_length=255),
        ),
    ]
