# Generated by Django 5.0.6 on 2025-10-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_processeddeposits_batch_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processeddeposits',
            name='transaction_type',
        ),
    ]
