# Generated by Django A.I. on 2025-10-21
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddeposits',
            name='transaction_ref',
            field=models.CharField(blank=True, null=True, max_length=255, help_text='Provider transactionRef for this item'),
        ),
    ]
