# Generated by Django 5.0.6 on 2025-10-22 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_processeddeposits_transaction_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('bank_code', models.CharField(max_length=255, verbose_name='Bank Code')),
                ('bank_account_number', models.CharField(max_length=255, verbose_name='Bank Account Number')),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_bank_details', to='webapp.projects')),
            ],
        ),
    ]
