# Generated by Django 5.0.6 on 2025-10-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_sourcebankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcebankdetails',
            name='bank_account_name',
            field=models.CharField(default='ABC', max_length=255, verbose_name='Bank Account Name'),
            preserve_default=False,
        ),
    ]
