# Generated by Django 4.1.7 on 2026-03-30 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_sourcebankdetails_bank_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_details', to='webapp.projects'),
        ),
        migrations.AlterField(
            model_name='sourcebankdetails',
            name='project',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_bank_details', to='webapp.projects'),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
